// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTracker.Infrastructure;

#nullable disable

namespace WorkoutTracker.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    partial class WorkoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutTracker.Domain.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Function")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Function = 0,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Function = 0,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3,
                            Function = 0,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 4,
                            Function = 0,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 5,
                            Function = 0,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 6,
                            Function = 1,
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = 7,
                            Function = 1,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 8,
                            Function = 1,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 9,
                            Function = 1,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 10,
                            Function = 1,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 11,
                            Function = 2,
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = 12,
                            Function = 2,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 13,
                            Function = 2,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 14,
                            Function = 2,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 15,
                            Function = 2,
                            Name = "Hip Thrust"
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Domain.ExerciseMuscle", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscle");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            MuscleId = 1
                        },
                        new
                        {
                            ExerciseId = 1,
                            MuscleId = 2
                        },
                        new
                        {
                            ExerciseId = 1,
                            MuscleId = 6
                        },
                        new
                        {
                            ExerciseId = 2,
                            MuscleId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            MuscleId = 2
                        },
                        new
                        {
                            ExerciseId = 3,
                            MuscleId = 2
                        },
                        new
                        {
                            ExerciseId = 3,
                            MuscleId = 6
                        },
                        new
                        {
                            ExerciseId = 4,
                            MuscleId = 3
                        },
                        new
                        {
                            ExerciseId = 5,
                            MuscleId = 6
                        },
                        new
                        {
                            ExerciseId = 6,
                            MuscleId = 7
                        },
                        new
                        {
                            ExerciseId = 6,
                            MuscleId = 5
                        },
                        new
                        {
                            ExerciseId = 7,
                            MuscleId = 7
                        },
                        new
                        {
                            ExerciseId = 8,
                            MuscleId = 7
                        },
                        new
                        {
                            ExerciseId = 8,
                            MuscleId = 4
                        },
                        new
                        {
                            ExerciseId = 9,
                            MuscleId = 5
                        },
                        new
                        {
                            ExerciseId = 10,
                            MuscleId = 4
                        },
                        new
                        {
                            ExerciseId = 11,
                            MuscleId = 8
                        },
                        new
                        {
                            ExerciseId = 11,
                            MuscleId = 10
                        },
                        new
                        {
                            ExerciseId = 12,
                            MuscleId = 9
                        },
                        new
                        {
                            ExerciseId = 12,
                            MuscleId = 10
                        },
                        new
                        {
                            ExerciseId = 13,
                            MuscleId = 8
                        },
                        new
                        {
                            ExerciseId = 14,
                            MuscleId = 9
                        },
                        new
                        {
                            ExerciseId = 15,
                            MuscleId = 10
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Front Delt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Side Delt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rear Delt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Glutes"
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Domain.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.ExerciseMuscle", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Domain.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.WorkoutSet", b =>
                {
                    b.HasOne("WorkoutTracker.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Domain.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("WorkoutTracker.Domain.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
